[project]
name = "syft-dataset"
version = "0.1.5"
description = "Syft Datasets"
authors = [{ name = "OpenMined", email = "info@openmined.org" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.10"

dependencies = [
    "pyyaml>=6.0.3",
    "syft-notebook-ui",
    "syft-perm",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/syft_datasets"]

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
]
